import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
// 1. นำเข้า Navigation เข้ามา
import Navigation from "../components/Navigation"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 2. ใส่ Navigation ไว้ด้านบนสุดของ body */}
        
        {/* 3. ส่วน main ควรมี pt (padding-top) เพื่อไม่ให้เนื้อหาถูก Header บัง */}
        <main className="flex-grow pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}